import type { NestTheme } from '@nest-ui/core';
import type { TableTheme } from '@nest-ui/table';
import type { DatePickerTheme } from '@nest-ui/datepicker';
import * as C from '@tokopedia/nest-color';

const { addAlpha } = C;

const pxToRem = (px: number) => px / 16 + 'rem';

type NestCompleteTheme = NestTheme & TableTheme & DatePickerTheme;

const defaultTokens: NestCompleteTheme = {
  'base-breakpoints': [0, 768, 1024, 1280],
  'base-fontFamily': "'Open Sauce One', sans-serif",
  'base-fontSize': [pxToRem(14)],
  'base-color': C.NN950,
  'base-lineHeight': [22 / 14],
  'base-backgroundColor': C.NN0,

  'accordion>title-color': C.NN950,
  'accordion-borderColor': C.NN50,
  'accordion>chevron-fill': C.NN950,

  'anchor-color': C.GN500,

  'avatar-size': [48],
  'avatar[xsmall]-size': [24],
  'avatar[small]-size': [32],
  'avatar[large]-size': [56],
  'avatar[xlarge]-size': [64],
  'avatar-borderRadius': [8],

  'button-borderRadius': [8],
  'button-height': [40],
  'button-paddingX': [7],
  'button-fontSize': [pxToRem(14)],
  'button-fontWeight': 'bold',
  'button[xsmall]-height': [24],
  'button[xsmall]-fontSize': [pxToRem(12)],
  'button[xsmall]>icon-size': [18],
  'button[small]-height': [32],
  'button[small]-fontSize': [pxToRem(12)],
  'button[large]-height': [48],
  'button[large]-fontSize': [pxToRem(16)],
  'button-borderColor': C.GN500,
  'button-background': C.GN500,
  'button-color': C.NN0S,
  'button:active-borderColor': C.GN600,
  'button:active-background': C.GN600,
  'button[ghost]-borderColor': C.GN500,
  'button[ghost]-background': C.NN0,
  'button[ghost]-color': C.GN500,
  'button[ghost]>loader-color': C.GN500,
  'button[ghost]:active-borderColor': C.GN600,
  'button[ghost]:active-background': C.GN50,
  'button[ghost]:active-color': C.GN600,
  'button[alternate]-borderColor': C.NN600,
  'button[alternate]-background': C.NN600,
  'button[alternate]:active-borderColor': C.NN700,
  'button[alternate]:active-background': C.NN700,
  'button[alternate][ghost]-borderColor': C.NN300,
  'button[alternate][ghost]-background': C.NN0,
  'button[alternate][ghost]-color': C.NN600,
  'button[alternate][ghost]:active-borderColor': C.NN400,
  'button[alternate][ghost]:active-background': C.NN50,
  'button[alternate][ghost]:active-color': C.NN600,
  'button[inverted]-borderColor': C.NN0S,
  'button[inverted]-background': C.NN0S,
  'button[inverted]-color': C.NN600S,
  'button[inverted]>loader-color': C.GN500S,
  'button[inverted]:active-borderColor': C.NN50S,
  'button[inverted]:active-background': C.NN50S,
  'button[inverted][ghost]-borderColor': C.NN0S,
  'button[inverted][ghost]-background': 'transparent',
  'button[inverted][ghost]-color': C.NN0S,
  'button[inverted][ghost]>loader-color': C.NN0S,
  'button[inverted][ghost]:active-borderColor': C.NN50S,
  'button[inverted][ghost]:active-color': C.NN50S,
  'button:disabled-borderColor': C.NN100,
  'button:disabled-background': C.NN100,
  'button:disabled-color': C.NN400,

  'bottomsheet-maxWidth': [600],
  'bottomsheet-background': C.NN0,
  'bottomsheet>title-color': C.NN950,
  'bottomsheet>buttonClose-color': C.NN950,
  'bottomsheet>handle-color': C.NN300,

  'chip[small]-height': [32],
  'chip[large]-height': [48],
  'chip[large]-borderRadius': [8],
  'chip[large]>image-size': [40],
  'chip[large]>image-borderRadius': [8],
  'chip[large]>image-margin': ['0px 4px 0px -8px'],
  'chip-background': C.NN0,
  'chip-borderColor': C.NN300,
  'chip-color': C.NN600,
  'chip:disabled-background': C.NN50,
  'chip:disabled-borderColor': C.NN50,
  'chip:disabled-color': C.NN400,
  'chip[active]-borderColor': C.GN400,
  'chip[active]-color': C.GN500,
  'chip[active]-background': C.GN50,

  'card-background': C.NN0,
  'card-borderColor': C.NN50,
  'card[active]-background': C.GN50,
  'card[disabled]-background': C.NN50,
  'card[disabled]-borderColor': C.NN50,
  'card-boxShadow': `0px 1px 4px ${addAlpha(C.NN1000S, 0.2)}`,

  'dateCalendar>buttonNav-color': C.NN950,
  'dateCalendar>dateButton-color': C.NN950,
  'dateCalendar>monthLabel-color': C.NN950,
  'dateCalendar>dayLabel-color': C.NN600,
  'dateCalendar>dateButton[today]-borderColor': C.GN500,
  'dateCalendar>dateButton[active]-background': C.GN500,
  'dateCalendar>dateButton[active]-color': C.NN0S,
  'dateCalendar>dateButton:disabled-color': C.NN400,
  'dateCalendar>dateNote-color': C.GN500,
  'dateCalendar>infoDot-color': C.TN500,
  'dateCalendar>dateButton[holiday]-color': C.RN500,

  'divider-color': C.NN50,

  'dropdown-background': C.NN0,
  'dropdown-borderColor': C.NN200,
  'dropdown-boxShadow': `0px 1px 4px 0px ${addAlpha(C.NN1000S, 0.2)}`,

  'container-paddingX': [16, 24],
  'container-maxWidth': [540, 720, 960, 1200],

  'checkbox-background': 'transparent',
  'checkbox-color': C.NN0S,
  'checkbox-borderColor': C.NN900,
  'checkbox:checked-background': C.GN500,
  'checkbox:disabled-borderColor': C.NN300,
  'checkbox:checked:disabled-background': C.NN300,

  'contentSwitcher-background': C.NN50,
  'contentSwitcher-color': C.NN600,
  'contentSwitcher>indicator-color': C.GN500,
  'contentSwitcher>option:checked-color': C.NN0S,

  'dialog>illustration-margin': ['0 0 16px', undefined, '0 0 24px'],
  'dialog>body-margin': ['0 0 16px', undefined, '0 0 24px'],
  'dialog>footer-margin': ['16px 0 0', undefined, '24px 0 0'],

  'inputgroup-borderColor': C.NN300,
  'inputgroup-color': C.NN950,
  'inputgroup>action-color': C.NN900,
  'inputgroup>append-color': C.NN600,
  'inputgroup>label-color': C.NN300,
  'inputgroup>message-color': C.NN600,
  'inputgroup:focus>label-color': C.NN600,
  'inputgroup:focus-borderColor': C.GN500,
  'inputgroup:disabled-borderColor': C.NN200,
  'inputgroup:disabled-color': C.NN400,
  'inputgroup:disabled>action-color': C.NN400,
  'inputgroup:disabled>append-color': C.NN400,
  'inputgroup:disabled>label-color': C.NN400,
  'inputgroup:disabled>message-color': C.NN400,
  'inputgroup[error]-borderColor': C.RN500,
  'inputgroup[error]>message-color': C.RN500,

  'image-background': C.NN100,

  'label-background': C.GN100,
  'label-color': C.GN500,
  'label[blue]-background': C.BN100,
  'label[blue]-color': C.BN500,
  'label[orange]-background': C.YN100,
  'label[orange]-color': C.YN500,
  'label[red]-background': C.RN100,
  'label[red]-color': C.RN500,
  'label[teal]-background': C.TN100,
  'label[teal]-color': C.TN500,
  'label[grey]-background': C.NN50,
  'label[grey]-color': C.NN600,
  'label[overlay]-background': C.addAlpha(C.NN900, 0.7),
  'label[overlay]-color': C.NN0S,

  'list>content-color': C.NN950,
  'list>description-color': C.NN600,
  'list>item-borderColor': C.NN100,

  'notification-background': C.RN600,
  'notification-color': C.NN0S,

  'modal-bleed': [16, undefined, 32],
  'modal-maxWidth': [undefined, 600, 800],
  'modal>header-margin': ['0 0 -16px', undefined, '0 0 -24px'],
  'modal>header-padding': [16, undefined, '24px 24px 16px'],
  'modal>body-padding': [16, undefined, 24],
  'modal-background': C.NN0,
  'modal>title-color': C.NN950,
  'modal>buttonClose-color': C.NN950,

  'progressBar[small]>track-height': [4],
  'progressBar[small]>track-paddingX': [2],
  'progressBar[small]>track-borderRadius': [2],
  'progressBar[large]>track-height': [8],
  'progressBar[large]>track-paddingX': [4],
  'progressBar[large]>track-borderRadius': [4],
  'progressBar>label-color': C.NN600,
  'progressBar>track-color': C.NN100,
  'progressBar>track[active]-color': C.GN400,

  'quantityEditor-borderRadius': [8],
  'quantityEditor-borderColor': C.NN300,
  'quantityEditor-background': C.NN0,
  'quantityEditor-color': C.NN950,
  'quantityEditor>spin-color': C.GN500,
  'quantityEditor>spin:disabled-color': C.NN400,
  'quantityEditor:focus-borderColor': C.GN500,
  'quantityEditor:disabled-borderColor': C.NN200,
  'quantityEditor:disabled-color': C.NN400,
  'quantityEditor[error]-borderColor': C.RN500,

  'radio-background': 'transparent',
  'radio-borderColor': C.NN900,
  'radio-color': C.GN500,
  'radio:checked-borderColor': C.GN500,
  'radio:disabled-color': C.NN300,
  'radio:disabled-borderColor': C.NN300,

  'rangeSlider>thumb-color': C.GN500,
  'rangeSlider>thumb-borderColor': C.NN0,
  'rangeSlider>track-color': C.NN100,
  'rangeSlider>track[active]-color': C.GN400,
  'rangeSlider>tick-color': C.NN300,
  'rangeSlider>tick[active]-color': C.GN100,
  'rangeSlider:disabled>track-color': C.NN100,
  'rangeSlider:disabled>thumb-borderColor': C.NN0,
  'rangeSlider:disabled>thumb-color': C.NN300,
  'rangeSlider:disabled>tick-color': C.NN100,
  'rangeSlider:disabled>track[active]-color': C.NN300,
  'rangeSlider:disabled>tick[active]-color': C.NN300,

  'ribbon-background': C.RN500,
  'ribbon-color': C.NN0S,
  'ribbon>fold-color': C.RN700S,
  'ribbon[blue]-background': C.BN500,
  'ribbon[blue]>fold-color': C.BN700S,
  'ribbon[yellow]-background': C.YN400,
  'ribbon[yellow]>fold-color': C.YN700S,
  'ribbon[teal]-background': C.TN500,
  'ribbon[teal]>fold-color': C.TN700S,
  'ribbon[green]-background': C.GN500,
  'ribbon[green]>fold-color': C.GN700S,
  'ribbon[purple]-background': C.PN500,
  'ribbon[purple]>fold-color': C.PN700S,

  'searchbar-background': C.NN0,
  'searchbar-borderColor': C.NN200,
  'searchbar-color': C.NN950,
  'searchbar>placeholder-color': C.NN600,
  'searchbar>buttonClear-color': C.NN500,
  'searchbar>icon-color': C.NN500,

  'select>option-color': C.NN950,
  'select>option[disabled]-color': C.NN400,
  'select>optionGroup-color': C.NN950,
  'select>optionGroup[disabled]-color': C.NN400,
  'select>option:hover-background': C.NN50,
  'select>option:active-background': C.NN100,
  'select>optionGroup:hover-background': C.NN50,
  'select>optionGroup:active-background': C.NN100,

  'shimmer-background': C.NN100,
  'shimmer-color': C.NN200,

  'table-color': C.NN950,
  'table>head-color': C.NN600,
  'table-borderColor': C.NN200,
  'table>row-background': C.NN0,
  'table-fontSize': ['0.875em'],
  'table-lineHeight': [1.5],

  'tabs>tab-color': C.NN600,
  'tabs>indicator-color': C.GN500,
  'tabs>tab[active]-color': C.GN500,

  'ticker-backgroundColor-error': C.RN50,
  'ticker-borderColor-error': C.RN200,
  'ticker-backgroundColor-warning': C.YN50,
  'ticker-borderColor-warning': C.YN200,

  'ticker-background': C.BN50,
  'ticker-borderColor': C.BN200,
  'ticker-color': C.BN400,
  'ticker>item-color': C.NN950,
  'ticker>title-color': C.NN950,
  'ticker>buttonClose-color': C.NN950,

  'ticker[warning]-background': C.YN50,
  'ticker[warning]-borderColor': C.YN200,
  'ticker[warning]-color': C.YN400,
  'ticker[warning]>item-color': C.NN950,
  'ticker[warning]>title-color': C.NN950,
  'ticker[warning]>buttonClose-color': C.NN950,

  'ticker[error]-background': C.RN50,
  'ticker[error]-borderColor': C.RN200,
  'ticker[error]-color': C.RN400,
  'ticker[error]>item-color': C.NN950,
  'ticker[error]>title-color': C.NN950,
  'ticker[error]>buttonClose-color': C.NN950,

  'timer-background': C.RN600,
  'timer-color': C.NN0S,
  'timer>title-color': C.NN0S,
  'timer[general]-background': C.RN50,
  'timer[general]-color': C.RN600,
  'timer[general]>title-color': C.NN950,
  'timer[yellow]-background': C.YN500S,
  'timer[informative]-background': C.TN50,
  'timer[informative]-color': C.TN600,
  'timer[informative]>title-color': C.NN950,
  'timer[idle]-background': C.NN100,
  'timer[idle]-color': C.NN400,
  'timer[idle]>title-color': C.NN400,

  'timerHighlight[small]-borderRadius': [4],
  'timerHighlight[small]-gap': [4],
  'timerHighlight[small]>flap-size': [24],
  'timerHighlight[small]>flap-fontSize': ['0.75rem'],
  'timerHighlight[small]>label-marginTop': [4],
  'timerHighlight[small]>label-fontSize': ['0.5rem'],

  'timerHighlight>flap-background': C.RN50,
  'timerHighlight>flap-color': C.RN600,
  'timerHighlight>separator-color': C.RN600,
  'timerHighlight>label-color': C.NN950,

  'timerHighlight[dark]>flap-background': C.RN600S,
  'timerHighlight[dark]>separator-color': C.RN600S,
  'timerHighlight[dark]>flap-color': C.NN0S,

  'tips-background': C.NN50,
  'tips-color': C.NN950,
  'tips>title-color': C.NN950,
  'tips-borderColor': C.NN300,
  'tips>icon-background': C.NN100,
  'tips>icon-color': C.NN300,

  'toaster[error]-background': C.RN600,
  'toaster-bleed': [16, '15vh 16px 16px'],
  'toaster-maxWidth': [600],
  'toaster-placement': ['bottom', 'top'],

  'tooltip-backgroundColor': C.NN900,
  'tooltip-color': C.NN100,

  'toggle-background': C.NN900,
  'toggle-color': C.NN0S,
  'toggle:checked-background': C.GN500,
  'toggle:disabled-background': C.NN100,
  'toggle:disabled-color': undefined,
  'toggle:checked:disabled-background': C.GN200,
  'toggle:checked:disabled-color': undefined,

  'typography[heading1]-fontSize': [pxToRem(24), pxToRem(38)],
  'typography[heading1]-lineHeight': [30 / 24, 46 / 38],
  'typography[heading1]-fontWeight': 800,

  'typography[heading2]-fontSize': [pxToRem(20), pxToRem(32)],
  'typography[heading2]-lineHeight': [26 / 20, 40 / 32],
  'typography[heading2]-fontWeight': 800,

  'typography[heading3]-fontSize': [pxToRem(18), pxToRem(28)],
  'typography[heading3]-lineHeight': [24 / 18, 34 / 28],
  'typography[heading3]-fontWeight': 800,

  'typography[heading4]-fontSize': [pxToRem(18), pxToRem(24)],
  'typography[heading4]-lineHeight': [24 / 18, 28 / 24],
  'typography[heading4]-fontWeight': 800,

  'typography[heading5]-fontSize': [pxToRem(18), pxToRem(20)],
  'typography[heading5]-lineHeight': [24 / 18, 26 / 20],
  'typography[heading5]-fontWeight': 800,

  'typography[heading6]-fontSize': [pxToRem(18)],
  'typography[heading6]-lineHeight': [24 / 18],
  'typography[heading6]-fontWeight': 800,

  'typography[display1]-fontSize': [pxToRem(16)],
  'typography[display1]-fontWeight': 400,
  'typography[display1]-lineHeight': [20 / 16],

  'typography[display2]-fontSize': [pxToRem(14)],
  'typography[display2]-fontWeight': 400,
  'typography[display2]-lineHeight': [18 / 14],

  'typography[display3]-fontSize': [pxToRem(12)],
  'typography[display3]-fontWeight': 400,
  'typography[display3]-lineHeight': [16 / 12],

  'typography[paragraph1]-fontSize': [pxToRem(16)],
  'typography[paragraph1]-fontWeight': 400,
  'typography[paragraph1]-lineHeight': [26 / 16],

  'typography-fontSize': [pxToRem(14)],
  'typography-fontWeight': 400,
  'typography-lineHeight': [22 / 14],

  'typography[paragraph3]-fontSize': [pxToRem(12)],
  'typography[paragraph3]-fontWeight': 400,
  'typography[paragraph3]-lineHeight': [18 / 12],

  'typography[small]-fontSize': [pxToRem(10)],
  'typography[small]-fontWeight': 400,
  'typography[small]-lineHeight': [12 / 10],
};

const darkTokens: NestCompleteTheme = {
  'card-background': C.NN50,
  'card-borderColor': C.NN200,
  'card[disabled]-background': C.NN100,
  'card[disabled]-borderColor': C.NN100,

  'label-background': C.GN500,
  'label-color': C.NN0S,
  'label[blue]-background': C.BN500,
  'label[blue]-color': C.NN0S,
  'label[orange]-background': C.YN500,
  'label[orange]-color': C.NN0S,
  'label[red]-background': C.RN500,
  'label[red]-color': C.NN0S,
  'label[teal]-background': C.TN500,
  'label[teal]-color': C.NN0S,
  'label[grey]-background': C.NN400,
  'label[grey]-color': C.NN0S,
  'label[overlay]-background': C.addAlpha(C.NN100, 0.7),

  'notification-background': C.RN400,

  'rangeSlider>tick[active]-color': C.GN900,

  'timer-background': C.RN400,
  'timer[general]>title-color': C.NN1000,
  'timer[informative]>title-color': C.NN1000,

  'tooltip-backgroundColor': C.NN1000,
  'tooltip-color': C.NN0,

  'toggle-background': C.NN100,
  'toggle:disabled-color': C.NN300,
  'toggle:checked:disabled-background': C.GN100,
  'toggle:checked:disabled-color': C.NN500,
};

const newFace: NestTheme = {
  'button-borderRadius': [12],
  'button[xsmall]-borderRadius': [8],
  'button[small]-borderRadius': [8],

  'card-borderRadius': [12],

  'checkbox-size': [20],
  'checkbox-bleed': [2],
  'checkbox-borderWidth': [1.5],
  'checkbox>checkmark-margin': [],
  'checkbox-borderColor': C.NN500,
  'checkbox:disabled-borderColor': C.NN200,
  'checkbox:disabled-background': C.NN50,
  'checkbox:disabled-color': C.NN300,
  'checkbox:checked:disabled-background': C.NN50,

  'chip-background': C.NN50,
  'chip-borderColor': C.NN50,
  'chip-borderRadius': [24],
  'chip>image-size': [20],
  'chip>image-margin': [2],
  'chip-[small]-borderRadius': [16],
  'chip[large]-borderRadius': [12],
  'chip[large]-gap': [8],
  'chip[large]>image-size': [48],
  'chip[large]>image-borderRadius': [0],
  'chip[large]>image-margin': ['-1px -1px -1px -12px'],

  'inputgroup-borderRadius': [12], //@TODO
  'inputgroup-paddingX': [12],
  'image-borderRadius': [12],

  'label-borderRadius': [8],
  'label-padding': ['4px 8px'],

  'quantityEditor-borderColor': C.NN300,
  'quantityEditor:disabled-borderColor': C.NN50,
  'quantityEditor:disabled-background': C.NN50,
  'quantityEditor[error]-borderColor': C.RN500,
  'quantityEditor>spin-color': C.NN900,
  'quantityEditor:focus>spin-color': C.GN500,
  'quantityEditor>spin:disabled-color': C.NN300,

  'radio-size': [20],
  'radio-bleed': [2],
  'radio-borderWidth': [1.5],
  'radio-padding': [3.5],
  'radio-borderColor': C.NN500,
  'radio:disabled-background': C.NN50,

  'searchbar-borderRadius': [12],

  'toggle-width': [44],
  'toggle-height': [24],
  'toggle-background': C.NN500,
  'toggle:disabled-background': C.NN50,
  'toggle:checked:disabled-background': C.GN100,
};

// some components need to switch the token based on theme
const nestTokopedia = (theme: string) => {
  const newTheme = Object.assign({}, defaultTokens, newFace);
  if (theme === 'dark') Object.assign(newTheme, darkTokens);
  return newTheme;
};

export default nestTokopedia;
