#!/bin/bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed

. "$(dirname "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Run bootstrap to reinstall dependencies if `pnpm-lock.yaml` is changed.
check_run pnpm-lock.yaml "pnpm install"
